name: build
on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]
jobs:
  info:
    name: Collect information
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.info.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Get info
        id: info
        # The tag name should be retrieved lazily, as tagging may be delayed.
        run: |
          TAG=$(git tag --points-at HEAD)
          if [[ ! -z "$TAG" ]]; then
            echo "::set-output name=new_tag::$TAG"
          fi
      - name: Show info
        env:
          NEW_TAG: ${{ steps.info.outputs.new_tag }}
        run: echo new_tag=$NEW_TAG
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - info
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Pack
        run: mv build reearth-web && tar -zcvf reearth-web.tar.gz reearth-web
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: reearth-web.tar.gz
  nightly:
    name: Release nightly
    runs-on: ubuntu-latest
    needs:
      - info
      - build
    if: "!needs.info.outputs.new_tag"
    env:
      ARTIFACT: reearth-web.tar.gz
      ARTIFACT_NEW: reearth-web_nightly.tar.gz
      ARTIFACT_CONTENTTYPE: application/gzip
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: Rename artifact
        run: mv ${{ env.ARTIFACT }} ${{ env.ARTIFACT_NEW }}
      - name: Release nightly
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.ARTIFACT_NEW }}
          artifactContentType: ${{ env.ARTIFACT_CONTENTTYPE }}
          commit: ${{ github.sha }}
          name: Nightly release
          body: ${{ github.sha }}
          prerelease: true
          tag: nightly
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - info
      - build
    if: needs.info.outputs.new_tag
    env:
      ARTIFACT: reearth-web.tar.gz
      ARTIFACT_NEW: reearth-web_${{ needs.info.outputs.new_tag }}.tar.gz
      ARTIFACT_CONTENTTYPE: application/gzip
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: Rename artifact
        run: mv ${{ env.ARTIFACT }} ${{ env.ARTIFACT_NEW }}
      - name: Download latest changelog
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: changelog-${{ needs.info.outputs.new_tag }}
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARTIFACT_NEW }}
          artifactContentType: ${{ env.ARTIFACT_CONTENTTYPE }}
          commit: ${{ github.sha }}
          name: ${{ needs.info.outputs.new_tag }}
          tag: ${{ needs.info.outputs.new_tag }}
          bodyFile: CHANGELOG_latest.md
  slack-notification-nightly:
    if: failure()
    name: Slack Notification
    needs:
      - nightly
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-notification-release:
    if: failure()
    name: Slack Notification
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
