name: main
on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.info.outputs.branch }}
      sha_short: ${{ steps.info.outputs.sha_short }}
      new_tag: ${{ steps.info.outputs.new_tag }}
      new_tag_short: ${{ steps.info.outputs.new_tag_short }}
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install golangci-lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
      - name: lint
        run: $(go env GOPATH)/bin/golangci-lint run --timeout=10m
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: Send coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
      - name: Get info
        id: info
        # The tag name should be retrieved lazily, as tagging may be delayed.
        run: |
          echo "::set-output name=branch::${GITHUB_REF##*/}"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          TAG=$(git tag --points-at HEAD)
          if [[ ! -z "$TAG" ]]; then
            echo "::set-output name=new_tag::$TAG"
            echo "::set-output name=new_tag_short::${TAG#v}"
          fi
  godoc:
    name: Build godoc
    runs-on: ubuntu-latest
    needs:
      - main
    if: "needs.main.outputs.branch && !needs.main.outputs.new_tag"
    env:
      REPO: github.com/reearth/reearth-backend
      REPO_NAME: reearth/reearth-backend
      ADDR: "localhost:8080"
      DIR: ${{ needs.main.outputs.branch }}
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download
      - name: install godoc
        run: go install golang.org/x/tools/cmd/godoc@latest
      - name: generate docs
        continue-on-error: true
        run: |
          godoc -http="$ADDR" &
          sleep 10
          wget -r -np -N -E -p -k "http://${ADDR}/pkg/${REPO}/"
      - name: replace urls
        run: |
          [ `find . -name "*.html" -type f | wc -l` -eq 0 ] && exit 1
          find ./${ADDR}/ -name "*.html" -print0 | xargs -0 sed -i \
            -e "s@http://${ADDR}/src/${REPO}@https://${REPO}/blob/main@" \
            -e "s@\"http://${ADDR}/pkg/\"@\"/${REPO_NAME}/${DIR}/pkg/${REPO}/\"@" \
            -e 's@<form @<form style="display:none" @' \
            -e "s@http://${ADDR}@/${REPO_NAME}/${DIR}@"
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.ADDR }}
          destination_dir: ${{ env.DIR }}
  build:
    name: Build and release
    runs-on: ubuntu-latest
    needs:
      - main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser for nightly
        if: "!needs.main.outputs.new_tag"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --snapshot
        env:
          GORELEASER_CURRENT_TAG: 0.0.0
      - name: Create GitHub release for nightly
        if: "!needs.main.outputs.new_tag"
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/reearth-backend_*.*
          commit: ${{ github.sha }}
          name: Nightly
          tag: nightly
          body: ${{ github.sha }}
          prerelease: true
          allowUpdates: true
      - name: Download latest changelog
        if: needs.main.outputs.new_tag
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: changelog-${{ needs.main.outputs.new_tag }}
      - name: Run GoReleaser
        if: needs.main.outputs.new_tag
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GORELEASER_CURRENT_TAG: ${{ needs.main.outputs.new_tag }}
      - name: Create GitHub release
        if: needs.main.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/reearth-backend_*.*
          commit: ${{ github.sha }}
          name: ${{ needs.main.outputs.new_tag }}
          tag: ${{ needs.main.outputs.new_tag }}
          bodyFile: CHANGELOG_latest.md
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs:
      - main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push nightly
        if: "!needs.main.outputs.new_tag"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=0.0.0-SNAPSHOT-${{ needs.main.outputs.sha_short }}
          tags: reearth/reearth-backend:nightly
          cache-from: type=registry,ref=reearth/reearth-backend:nightly
          cache-to: type=inline
      - name: Build and push release
        if: needs.main.outputs.new_tag
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ needs.main.outputs.new_tag_short }}
          tags: |
            reearth/reearth-backend:${{ needs.main.outputs.new_tag_short }}
            reearth/reearth-backend:latest
          cache-from: type=registry,ref=reearth/reearth-backend:latest
          cache-to: type=inline
  slack-notification:
    if: always()
    name: Slack Notification
    needs:
      - main
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
